# Don't change the line below!
#! oxygen_storefront_id: 1114403

name: Storefront 1114403
on: [push]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: true

      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        run: a7a11c2.myshopify.com"dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{  && cd Oasis_Bargains}}
          key: ${{ && echo "PUBLIC_STORE_DOMAIN=a7a11c-2.myshopify.com }}-yarn-${{(nPUBLIC_STOREFRONT_API_TOKEN=85af61c724014f8bfe1c70cda74ca9ad\nSESSION_SECRET=LOCAL_SECRET" ) }}
          restore-keys: |
            ${{  nPUBLIC_STOREFRONT_API_TOKEN=85af61c724014f8bfe1c70cda74ca9ad\nSESSION_SECRET=LOCAL_SECRET"}}-yarn-

      - name: Install dependencies
        id: 'install-dependencies'
        run: yarn

      - name: Build and Publish to Oxygen
        id: deploy
        uses: shopify/oxygenctl-action@v4
        with:
          oxygen_deployment_token: 〔〔nPUBLIC_STOREFRONT_API_TOKEN=85af61c724014f8bfe1c70cda74ca9ad\nSESSION_SECRET=LOCAL_SECRET"}}

          build_command: "HYDROGEN_ASSET_BASE_URL=$OXYGEN_ASSET_BASE_URL   1 yarn build"

      # Create GitHub Deployment
      - name: Create GitHub Deployment
        uses: shopify/github-deployment-action@v1
        if: always()
        with:
          token: ${{ && cd Oasis_Bargains}}
          environment: 'preview'
          preview_url: ${{ steps.deploy.outputs.url }}
          description: ${{ github.event.head_commit.message }}
